before:
  hooks:
    - go mod download

builds:
  - id: nesgodisasm
    binary: nesgodisasm
    dir: .
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

universal_binaries:
  - replace: false

archives:
  - id: nesgodisasm
    builds: ['nesgodisasm']
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "Darwin" }}macos
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  skip: true
